### ISSUE TITLE
module load autocomplete broken on osx

### ISSUE THREAD

**Issue by arp2600** [cea-hpc/modules#178]
Auto complete for module load requires the sed `-r` flag, which isn't supported by the sed on osx.
Typing `module load` and then tab, produces the following output:
```
$ module load sed: illegal option -- r
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
       q
```

This problematic sed command is in `init/bash_completion`
```
_module_not_yet_loaded() {
    _module_avail | sort | sed -r "\%^(${LOADEDMODULES//:/|})$%d"
}
```

Removing the `-r` flag seems to fix the issue. I have tested this using the default osx sed and gnu-sed. On gnu-sed, behaviour didn't appear to change when removing the flag.

**Comment by xdelaruelle** [comment]
`-r` flag is mandatory to make use of alternation `|` in regexp. Removing this `-r` flag does not lead to an error message but without it sed is not able anymore to filter out loaded modules from available module list.

Will use `-E` instead of `-r`, which is an alias for `-r` on Linux system and recognized on OS X and BSDs to enable extended regular expression.
