### ISSUE TITLE
Ignoring errors coming from "module load" commands in modulefile

### ISSUE THREAD

**Issue by kw101uk** [cea-hpc/modules#197]
Hi (first request here)

We use modules extensively, but are still using the 3.2.6a release (C).  Ive spent some time trying to match the functionality we have between the old version and the 4.1.3 tcl version.

We have some modules that simply contain lists of modules to load.

e.g.
modulefile : collection1
contains

> #%Module1.0
> 
> module load mod1
> module load mod2

In the C version, if module "mod1" contained a "break" statement, it is not loaded, but the remaining modules in "collection1" are loaded.
In the tcl version if module "mod1" contained a "break" statement, nothing is loaded, and a load on module "mod2" is not even attempted

Ive checked using "compatibility" mode in 4.1.3 and the C version still functions as it did in 3.2.6a.

Is this behavior expected?

Thanks
Keith

**Comment by xdelaruelle** [comment]
Hi Keith,

What you describe is the expected behavior. Quoting the [differences between version 3.2 and 4](https://modules.readthedocs.io/en/stable/diff_v3_v4.html#module-sub-commands) document:

> In case of modulefile loading another modulefile, if sub-modulefile load fails calling modulefile will still be loaded on compatibility version whereas Modules 4 will also abort calling modulefile load.

This is done to consistently evaluate the whole modulefile and abort when an error is detected.

Maybe a ``--ignore-error`` optional flag to ``module load`` command would help here to continue processing the main modulefile even if submodulefile load attempt failed.

By the way, there is now a specific collection handling system. I suggest you to look at the ``save`` and ``restore`` module commands.

Regards,
Xavier

**Comment by kw101uk** [comment]
Thanks Xavier

That explains it.  
For the moment i think we will have to stay with the C version (legacy use of these "modules loading modules").  A "--ignore-error" option sounds like a great solution for us though.

I see there has been some talk of "shared collections" on the issues page which sounds like what we would need for our environment.

Regards
Keith

**Comment by wenzler** [comment]
Please add a g_ variable to allow setting it via siteconfig globally, too.
Thanks!

**Comment by xdelaruelle** [comment]
Thinking about this issue, I believe that in the end we should just rely here on the [`catch`](https://www.tcl.tk/man/tcl8.4/TclCmd/catch.html) Tcl command to continue the modulefile evaluation in case of a failed `module load` command in that moduelfile.

```
#%Module1.0
catch {module load mod1}
catch {module load mod2}
```

I will add this information in the  *differences between version 3.2 and 4* document.
