### ISSUE TITLE
new modulefile command to set that module could not be unloaded (sticky)

### ISSUE THREAD

**Issue by xdelaruelle** [cea-hpc/modules#269]
The concept of surviving “purge” or “unload” looks rather like such modules being *sticky*. Such an attribute needs to be flagged in “module list” output, ideally including when “—terse” is active (for parsing). Come to think about it, I’d say such an attribute might be set-able by a declaration, not a code snippet.

_Originally posted by @mgsternberg in https://github.com/cea-hpc/modules/issues/267#issuecomment-489461154_

**Comment by mgsternberg** [comment]
Xavier,

I wasn't sure if a "sticky" concept would add much functionality, because of my perspective (as shaped by necessity) of using `module clear` for system-level provisioning. But it's a reasonable design decision of what to expose to users. A "sticky" concept allows users to see not only names but also versions of modules so provisioned, and that could be useful in support inquiries. Importantly, a sticky concept opens the door to *unload* when desired, after all, which cannot be done for "disowned" modules.

Thus, I think there needs to be an override flag to `unload` and `purge` actions to affect sticky modules as well. Like in #268, a `-f, --force` option would mesh with Unix conventions. Could this work?

You gave `-f` already a meaning for  `unload` and `switch`. Both require *named* modules, and implying unstick as well surely goes along with the user's expressed intention. By contrast, `purge` was not yet affected by `-f`, so that seems a reasonable addition.

Could a user want to `module -f purge` a botched lineup but want to keep "system"/"sticky" modules? If so, perhaps a different option than `-f` is needed after all, or `-f` be required to be *doubled* to overcome "sticky", similar in spirit of how `-v, --verbose` is treated in many applications.

**Comment by xdelaruelle** [comment]
Through the new *module tag* mechanism, 2 tags will have a special meaning: `sticky` and `super-sticky`. Both tags will forbid the unload of tagged module unless if this module is reloading. `sticky` modules will also be unloaded if the unload action is forced. Even if forced the `super-sticky` modules cannot be unloaded.
