### ISSUE TITLE
Behaviour change for module-info between 3.2.10 and latest...is it configurable?

### ISSUE THREAD

**Issue by matthew-page** [cea-hpc/modules#297]
I'm migrating my company up from 3.2.10 up to 4.3.0 (but 4.3.1 is ok as well) and I notice that "module-info name" behavior has changed to return fullpath if fullpath was given...it used to return the relative short part if its in MODULEPATH.  Is there a config option to get prior behavior so my years of history which presumed prior doesn't break?

in the modulefile :
     set modulefile_name [module-info name]
     setenv THENAME $modulefile_name

and $MODULEPATH has :
     /some/full/path/to

in 3.2.10 :
     % module show /some/full/path/to/file
    /some/full/path/to/file:
    setenv          THENAME    file

in 4.3.0 :
     % module show /some/full/path/to/file
    /some/full/path/to/file:
    setenv          THENAME /some/full/path/to/file

**Comment by xdelaruelle** [comment]
When loaded by its full pathname, module is then identified by this fully qualified name (as basename does not necessarily enables to distinguish it from other loaded modules). ``module-info name`` returns identification name of modulefile that is why since version 4 it returns full pathname for modulefiles specified this way.

To help you keeping the behavior of the compatibility version, I will provide a cookbook recipe that will provide the code to override the definition of the ``module-info`` command to get the old behavior back.
