### ISSUE TITLE
GNU sed 4.1.5 doesn't have -E

### ISSUE THREAD

**Issue by alef** [cea-hpc/modules#317]
Replacing with `-r` or `--regexp-extended` works for `init/bash_completion`

**Comment by xdelaruelle** [comment]
Thanks for the report. Option `-E` is used on purpose to achieve portability across OSes, see b68e44ef.

I was not aware this `-E` option was rather recent on GNU sed.

The quick fix: I will add a check at configure step to detect if `sed -E` is supported on the platform and fallback to `sed -r` otherwise.

A more sustainable solution: directly use the output from `module avail` as input for completion scripts without need to call for external commands like `sed`.
