### ISSUE TITLE
module unload/load inside modulefile fails

### ISSUE THREAD

**Issue by reinh-bader** [cea-hpc/modules#333]
### Describe the bug
If a module file pp/42 contains a sequence

module unload b/1
module unload a/1
module load a/2
module load b/2

(necessary because (1) a/1 and b/1 are loaded by default in the environment, and (2) because b has a as a prereq) the following error is issued:

Loading a/2
  ERROR: Conflicting 'pp/42' is loading

Loading pp/42
  ERROR: Load of requirement 'a/2' failed

The module is referring to itself, which appears spurious 

### To Reproduce

```
unpack the attached archive repro.tar.gz and run the script 
./repro.sh
Note that it assumes the module command is inherited into the new shell.
```

Location and content of any modulerc or modulefile involved:

```
All module files are packaged into the archive
```

### Expected behavior

After loading the module pp/42 the following modules should be loaded
a/2
b/2
pp/42

### Error and debugging information

```
Contained in the archive as file DEBUG.txt
```

### Modules version and configuration

```console
$ module --version
Modules Release 4.4.1 (2020-01-03)
$ module config --dump-state
see file STATE.txt in archive
```

### Additional context

Attached file (compressed UNIX archive)
[repro.tar.gz](https://github.com/cea-hpc/modules/files/4417299/repro.tar.gz)

**Comment by xdelaruelle** [comment]
Example `pp/42` modulefile does:

```
module unload b 
module unload a
module load a/2 
module load b/2
```

Which declares that `pp/42` is conflicting with any version of `b` or any version of `a` (as any `b` or `a` module should be unloaded when `pp` loads). Then a requirement is declared on `a/2` and `b/2`. But those 2 modules are also matching the conflict declared so an error is obtained when trying to load them.

Changing the `module unload` statements to a more specific version of `a` and `b` solves the issue encountered as conflict is this way defined with the specific version only and not with all versions of `a` and `b`:

```
module unload b/1 
module unload a/1
module load a/2 
module load b/2
```

With the above constraints defined within `pp` modulefile, below is the output of the `repro.sh` script:

```console
$ bash repro.sh
Currently Loaded Modulefiles:
 1) a/1   2) b/1  
Loading pp/42
  Unloading conflict: b/1 a/1
  Loading requirement: a/2 b/2
Currently Loaded Modulefiles:
 1) a/2   2) b/2   3) pp/42
```

**Comment by xdelaruelle** [comment]
There are plans to simplify such definition in the future, with the addition of a new mechanism to the [automated module handling mode](https://modules.readthedocs.io/en/latest/module.html#envvar-MODULES_AUTO_HANDLING). This new mechanism will be called *Conflict Unload* and when enabled it will swap loaded versions of modulefiles to other versions matching the requirement of loading module.

So by just adding in `pp/42` modulefile:
```
module load a/2
module load b/2
```

*Conflict Unload* mechanism will unload `a/1` to load `a/2` and unload `b/1` to load `b/2` (because both modules state that only one version of `a` and `b` could be found loaded in the environment.

Ticket #242 tracks this new feature addition.

**Comment by reinh-bader** [comment]
Thanks for the explanation. The new feature will be valuable in reducing the maintenance effort, since loaded defaults can change.
