### ISSUE TITLE
Extension for Modulefiles

### ISSUE THREAD

**Issue by rchurt** [cea-hpc/modules#353]
### Is your feature request related to a problem? Please describe.
When looking through a folder containing Modulefiles and other files, it can be very hard to figure out which files are Modulefiles. The downside of this is that if I've tried to create a module, I can't be sure that the process was successful if I don't know what the name of the Modulefile should be, and I can't look at the Modulefile to see what it does.

### Describe the solution you'd like
Adding an extension like `.mf`, `.mod`, or `.modfile` to Modulefiles would make them easier to find. It wouldn't be necessary to go  back through and change all of the existing Modulefiles to have the extension, but perhaps it would be worth doing it for some of the most important ones (for example, `dot` to `dot.mf`), and starting to do it for new ones from now on.

**Comment by xdelaruelle** [comment]
Modulefile are expected to be found in modulepaths, which are directory storing modulefiles. These directories are enabled with `module use /path/to/modulepath/dir` commands, which make the modulefiles stored in these enabled directories reachable for `module` command.

So basically you know that the files found in modulepaths are modulefiles. There is no extension needed. And this is important to have all your modulefiles gathered at the same place to avoid expensive filesystem scan.

To be recognized as a modulefile, the rule is that such file should start with the `#%Module` magic cookie. Otherwise it is ignored by the `module` command. Newer version of the `file` utility are able to tell if a file is a modulefile (based on the magic cookie).

Modulefile are just Tcl script file with additional Tcl commands that are described in [documentation](https://modules.readthedocs.io/en/stable/modulefile.html). By reading a modulefile with a text editor one could determine what the modulefile does (most of the time setting environment variable, adding directory to existing path-like environment variable).

```console
$ cat /usr/share/Modules/modulefiles/dot
#%Module
module-whatis   "adds `.' to your PATH environment variable"
append-path     PATH            .
```

By using directly the command that translates a modulefile into shell commands (`modulecmd.tcl`) you can see what the modulefile does to your shell environment when it is loaded:

```console
$ $MODULES_CMD sh load /usr/share/modules/modulefiles/dot
_LMFILES__modshare=/usr/share/modules/modulefiles/dot:1; export _LMFILES__modshare;
LOADEDMODULES_modshare=/usr/share/modules/modulefiles/dot:1; export LOADEDMODULES_modshare;
PATH=/usr/bin:/usr/sbin:.; export PATH;
_LMFILES_=/usr/share/modules/modulefiles/dot; export _LMFILES_;
LOADEDMODULES=/usr/share/modules/modulefiles/dot; export LOADEDMODULES;
PATH_modshare=/usr/sbin:1:/usr/bin:1:.:1; export PATH_modshare;
test 0;
```

**Comment by rchurt** [comment]
Got it, that makes sense. I think my problem was that I was expecting the modulefiles to be contained in the packages I downloaded, and that all I would need to do is to find them. I was using `module use /path/to/modulepath/dir && echo $MODULEPATH` and even though that showed that the directories had been added, the output of `module avail` didn't change. However, it seems like usually modulefiles aren't contained in packages, and you need to make them yourself (though certainly correct me if I'm wrong).

**Comment by xdelaruelle** [comment]
> However, it seems like usually modulefiles aren't contained in packages, and you need to make them yourself (though certainly correct me if I'm wrong).

This is correct. In your situation I think someone (maybe the author of the script you use) should indicate where to find this `Perl` modulefile. (as like you say, it does not come with the Perl packages you have installed).

**Comment by xdelaruelle** [comment]
I assume that things have been clarified so this issue can be closed.
