### ISSUE TITLE
comment handling not working as in modules 3

### ISSUE THREAD

**Issue by wenzler** [cea-hpc/modules#402]
### Describe the bug

Comments are not supported like they were in modules 3

### To Reproduce

Have module with something like
setenv foo bar # comment

### Expected behavior
No error

### Error and debugging information

```
Module ERROR: wrong # args: should be "setenv var val"
      invoked from within
  "setenv          MGC_BIN         $mgc_home/bin                   #comment"
...
```

### Additional context
Tested with modules 4.5.2 and 4.7.1

**Comment by xdelaruelle** [comment]
Could you provide the full content of the modulefile to reproduce the issue?

**Comment by wenzler** [comment]
This is just a minor incompatibility and should be mentioned as its probably just working by accident on v3

> #%Module1.0
> setenv foo "bar" #comment
> prepend-path PATH ENV(foo)

**Comment by xdelaruelle** [comment]
Same behavior is obtained with bare Tcl script:

```shell
$ cat test.tcl
set var val #comment
$ tclsh test.tcl
wrong # args: should be "set varName ?newValue?"
    while executing
"set var val #comment"
    (file "test.tcl" line 1)
```

The Tcl community [recommends using `;#` for inline comment](https://wiki.tcl-lang.org/page/comment).

Modules since version 4.0 evaluates full modulefile script as a Tcl script. Specific modulefile read and evaluation was performed previously (on Modules 3.2), which must explain why the error were not obtained on old version of Modules.

**Comment by wenzler** [comment]
Yeah, as said - not really a bug but a v3 feature :)
