### ISSUE TITLE
module unload causes conflict

### ISSUE THREAD

**Issue by shareefj** [cea-hpc/modules#448]
Hi,

I've been debugging a conflict that occurs when `module unload`'ing a module.  This seems to have appeared somewhere between v3 and v5 and from my limited browsing of issues, might be related to some of the `prereq` changes that came in to play in v4.2?

We tend to have a project modulefile that sets up a user's environment.  This does `module load`'s for all tools we use.  However, I'm seeing a conflict when moving to v5 that I don't understand.  A fix that seems to work is using `module unload --not-req <module>` but I don't understand why.  Can someone explain what is wrong with the following module file.

So my directory looks like:

```
.
└── modulefiles
    ├── proj
    └── vendor
        └── tool
            └── v1.0

3 directories, 2 files
```

The `proj` modulefile looks like:

```
#%Module1.0

module unload --not-req vendor/tool

if [ module-info mode load ] {
    module load vendor/tool/v1.0
}
```

and the `v1.0` module file looks like:

```
#%Module1.0

module-whatis "A magical tool"

set module_name [ module-info name ]

conflict vendor/tool

if [ module-info mode load ] {
    puts stderr "Loading module $module_name"
} else {
    puts stderr "Unloading module $module_name"
}
```

If I try to load `proj` without the `--not-req` switch, I get:

```
> module load proj
Loading module vendor/tool/v1.0

Loading vendor/tool/v1.0
  ERROR: Conflicting proj is loading

Loading proj
  ERROR: Load of requirement vendor/tool/v1.0 failed
```

So why is that?  I think the intent from the original author was to make sure that any previous modules from `vendor` were removed before loading the new one.  Is that now a good idea now?  What is a better method?

**Comment by xdelaruelle** [comment]
Hi @shareefj,

Using a `module unload` in a modulefile means not wanting this module to unload loaded along the modulefile expressing this dependency. Since Modules 4.2, such requirement is also satisfied after module being loaded: the conflicting message you get comes from that mechanism.

Using the `--not-req` command-line switch helps to express that a module load or unload command used in a modulefile does not imply a requirement to satisfy even after the module being loaded.

In your case, it seems you want to ensure that this is the version `1.0` of `vendor/tool` which is loaded, not another version. Instead of doing a `module unload` then a `module load`, you may use a module switch: `module switch vendor/tool vendor/tool/1.0`. `switch` sub-command will unload any other version loaded of `vendor` without making that a conflict as the module to switch-on is just another version of the same module name.

**Comment by shareefj** [comment]
@xdelaruelle 

Thanks for that.  Just to clarify your first sentence as I got a bit lost.

You said, "Using a `module unload` in a modulefile means not wanting this module to unload loaded along the modulefile expressing this dependency."

So I think you're saying that since version 4.2, all `module load` and `module unload` commands are effectively evaluated together?  So having both a `module unload a` and a subsequent `module load a` in the same modulefile causes the conflict?  Whereas in versions previous to 4.2, that would have been ok.  It would have performed the `module unload a` first and then the subsequent `module load a` would have been evaluated without the dependency.

I understand your point about using `switch`.  I think that was the intent in this modulefile but if the aim was to just start with a clean environment, then is it better to just use `module purge`?

**Comment by xdelaruelle** [comment]
> So I think you're saying that since version 4.2, all `module load` and `module unload` commands are effectively evaluated together? So having both a `module unload a` and a subsequent `module load a` in the same modulefile causes the conflict? Whereas in versions previous to 4.2, that would have been ok. It would have performed the `module unload a` first and then the subsequent `module load a` would have been evaluated without the dependency.

Since v4.2, a `module load` is interpreted as a `module load` + `prereq` and a `module unload` is interpreted as a `module unload` + `conflict`. Extra `prereq`/`conflict` are skipped if `--not-req` option is set or if global configuration option [implicit_requirement](https://modules.readthedocs.io/en/latest/module.html#mconfig-implicit_requirement) is disabled.

If there is a `module unload a` then a `module load a` in the same modulefile, an error is obtained as the `module load` part tries to load `a` that was just declared a conflict by `module unload` right before.

> I understand your point about using `switch`. I think that was the intent in this modulefile but if the aim was to just start with a clean environment, then is it better to just use `module purge`?

`purge` sub-command cannot be used within modulefiles. To define a complete environment, [module collections](https://modules.readthedocs.io/en/latest/module.html#collections-1) should be used.

**Comment by shareefj** [comment]
Clear. Thanks a lot.
