### ISSUE TITLE
Highlighting modulefiles specified by tool admin.

### ISSUE THREAD

**Issue by wanlinwang** [cea-hpc/modules#504]
### Describe the solution you'd like

My users module load tens of tool/version at a time. Some of those tool/version are important. He want the important tools to be highlighted. Could we do that?

**Comment by xdelaruelle** [comment]
You can do that with module tags and specific colored output defined for these tags.

At the root of your modulepath, add a `.modulerc` file to define tags on your important modules:

```console
$ cat /path/to/modulefiles/.modulerc 
#%Module
module-tag important foo
```

In this above example, the `important` tag is set on all `foo` modules:

```console
$ module av
---------------- /path/to/modulefiles ----------------
bar/1  bar/2  foo/1 <important>  foo/2 <important>  

Key:
modulepath  <module-tag>
```

Instead of displaying the tag name along the module name, you can define a *graphic rendition* that represents tag over the module name. This definition should be added to the `colors` configuration with the syntax `tagname=graphic_rendition`. For instance to represent  `important` tag with bold character:

```console
$ module config colors +important=1
```

If use do not yet use Modules version 5.3, you should set the whole existing `colors` value and append `:important=1` at the end of it.

Once set, `foo/1.0` and `foo/2.0` will be represented with bold font on module avail output.

Instead of bold font, you can define other graphic rendition like font color or background color. See https://en.wikipedia.org/wiki/ANSI_escape_code#SGR_(Select_Graphic_Rendition)_parameters
