### ISSUE TITLE
Installation directory differs on platforms

### ISSUE THREAD

**Issue by shareefj** [cea-hpc/modules#528]
I've been trying to write a script that makes use of environment modules and noticed that the installation folder name differs across distributions.  Is this expected?

Ubuntu 22.04 seems to use /usr/share/Modules while Rocky 8.6 uses /usr/share/modules.  Are there any other installation paths that I should cope with?

**Comment by xdelaruelle** [comment]
Distributions have their own location to install stuff and for a package that exists since a long time like environment-modules, you may encounter differences like that. RedHat-like distributions install Modules in /usr/share/Modules, on Debian-like distributions /usr/share/modules is used.

But considering what you want to do, once Modules is installed you should be able to use the "module" command in your shell script.

If "module" command is not available by default when running your script there may be an issue with your installation or some configuration should be achieved.

When running your script what is the result when it executes the "module" command?
