### ISSUE TITLE
The "module" function defined in R initialization script hangs forever when loading a module that does not exist

### ISSUE THREAD

**Issue by fplazaonate** [cea-hpc/modules#542]
### To Reproduce

1. Open an R interpreter (version 4.4.1)
2. Run the following commands
```
source('/usr/share/modules/init/r.R')
module('load toto')
```

**Comment by xdelaruelle** [comment]
I am able to reproduce this issue on my side.

It looks like there is a wrong interaction with the output pager. I will investigate.

In the mean time, you may disable the pager prior running `R`:

```console
$ module config pager cat
```

**Comment by xdelaruelle** [comment]
Issue occurs when stderr content is sent through the configured pager. This issue was not there on R `4.4.3`. So a change introduced on R between versions `4.4.3` and `4.4.1` makes this issue appear.

Anyway, it seems more caution not to use pager when running `modulecmd.tcl` for script language. So I will disable pager when `modulecmd.tcl` is run for *python*, *perl*, *ruby*, *tcl*, *cmake*, *r* and *lisp*.
