### ISSUE TITLE
rockylinux8.10: ERROR: couldn't load file "/usr/lib64/libtclenvmodules.so": /usr/lib64/libtclenvmodules.so: wrong ELF class: ELFCLASS64

### ISSUE THREAD

**Issue by lubuhan** [cea-hpc/modules#543]
OS: Rockylinux8.10
gcc: version 8.5.0 20210514 (Red Hat 8.5.0-22) (GCC)
```bash
[root@master ~]# source /usr/share/Modules/init/bash
ERROR: couldn't load file "/usr/lib64/libtclenvmodules.so": /usr/lib64/libtclenvmodules.so: wrong ELF class: ELFCLASS64
      while executing
  "load [file normalize [getConf tcl_ext_lib]] Envmodules"
  Please report this issue at https://github.com/cea-hpc/modules/issues
```

**Comment by lubuhan** [comment]
environment-modules.x86_64: 4.5.2-4.el8

**Comment by lubuhan** [comment]
After uninstalling glibc.i686, this software can now be used.

**Comment by xdelaruelle** [comment]
You obtain this error because `tclsh` from tcl.i686 package is trying to load the `/usr/lib64/libtclenvmodules.so` library built for x86_64.

Unfortunately the EL8 distribution is not providing `environment-modules.i686` that would have help in your case.

But if you use `tclsh` from tcl.x86_64 package, even with glibc.i686 installed, `module` will run smoothly.
