### ISSUE TITLE
getAbsolutePath

### ISSUE THREAD

**Issue by Alexwxwu** [cea-hpc/modules#545]
### Describe the bug
ERROR: error getting working directory name: no such file or directory
      while executing
  "pwd"
      (procedure "getAbsolutePath" line 9)
      invoked from within
  "getAbsolutePath $::argv0"
      (procedure "cmdModuleAutoinit" line 11)
      invoked from within
  "cmdModuleAutoinit"
      (procedure "module" line 325)
      invoked from within
  "module autoinit"
      ("eval" body line 1)
      invoked from within
  "eval $execcmdlist"
  Please report this issue at https://github.com/cea-hpc/modules/issues

**Comment by xdelaruelle** [comment]
Thanks for your report. You obtain this issue because you are running the `module` command whereas the current working directory of you shell session has been removed.

By moving out of the removed directory (`cd` command), the error will disappear.

Such issue was already reported on #457. An improved error message has been added on version 5.1.1 of Modules.
