### ISSUE TITLE
can't fork child process when using VScode SSH

### ISSUE THREAD

**Issue by olympus-terminal** [cea-hpc/modules#546]
When using VScode SSH (or Cursor), all of my login sessions on other terminals start reporting:

WARNING: couldn't fork child process: resource temporarily unavailable
ERROR: couldn't fork child process: resource temporarily unavailable
      while executing
  "exec logger -t module "[get-env USER]: $command [join $args]""
      (procedure "module" line 3)
      invoked from within
  "module autoinit"
      ("eval" body line 1)
      invoked from within
  "eval $execcmdlist"
  Please report this issue at https://github.com/cea-hpc/modules/issues
bash: fork: retry: Resource temporarily unavailable
bash: fork: retry: Resource temporarily unavailable
bash: fork: retry: Resource temporarily unavailable
bash: fork: retry: Resource temporarily unavailable
bash: fork: Resource temporarily unavailable
bash: fork: retry: Resource temporarily unavailable

And my HPC session is effectively blocked.

**Comment by xdelaruelle** [comment]
Many thanks for your report. `module` command is failing because it hits some resource limitation. It seems that you reached some limits on your login session. It may either be the number of opened file descriptor or number of processes.

You may find some explanation of such issue here: https://unix.stackexchange.com/questions/205016/fork-retry-resource-temporarily-unavailable

I suggest you to get in touch in the system administrator of the machine you are running on. This person should now the limits that have been configured on this system and should explain you how to proceed.
