### ISSUE TITLE
spreading loaded module setup in sub-shells

### ISSUE THREAD

**Issue by xdelaruelle** [cea-hpc/modules#86]
I have a number of module using set-alias, they work with the 3.2.10 C version. With both 1.775 and 1.832 the behaviour is a little odd. Everything works correctly if I run a "module load" from the command line, or add to my .cshrc and ssh to the server. All great so far.

We use xfce as our desktop envirnoment (this runs under NoMachine). If you create a new desktop session the modules are loaded (module list shows the correct thing), but set-alias statements do not work under 1.775 or 1.832. If I switch back to 3.2.10 the alias appear again. If I replace the "module load" with "module switch" set-alias also works under 1.775 and 1.832.

OS: CentOS 7
Shell: tcsh

Reported by: crdxdx

**Comment by bclmary** [comment]
Same problem with a xfce session through x2go (remote graphic desktop) using module v4.2.1.
Through ssh connection, modules and aliases works well. Through xfce/x2go, aliases are lost.
Aliases are defined using "set-alias". Also tested using "set-function" : the functions are not transmitted also.
The proposed workaround using "purge" before loading the modules (in user's .bashrc or .modulerc) is not a solution. The remote desktop, just complains that it cannot unalias because the aliases are not present...

**Comment by xdelaruelle** [comment]
The initialization of Modules will be adapted to perform a `module refresh` when a loaded environment is found defined. This way when a sub-shell initializes Modules but inherits the loaded modules from its parent shell, the refresh will re-applies the shell aliases and functions defined in loaded modules that were not inherited from the parent shell.
